# Generated by Django 3.2.10 on 2022-01-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220123_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
    ]
