# Generated by Django 3.2.10 on 2022-01-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
