# Generated by Django 3.2.10 on 2022-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
