# Generated by Django 3.2.10 on 2022-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(default='List title', max_length=300),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(default='Step title', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Task title', max_length=300),
        ),
    ]
